### ISSUE TITLE
新增插件check_rwx-suid

### ISSUE THREAD

**Issue by phantom11235** [AntSword-Store/AntSword-Store.github.io#6]
## 新插件上架申请

- [x] 我确定我推出的插件是为了方便网站管理，而不是用于非法用途
- [x] **我保证该插件无后门植入**
- [x] 我确定不存在相同或者相似度很高的插件
- [x] 插件已经在本地测试成功且无较严重Bug
- [x] 我已经按照要求在插件源代码中编写了规范的 package.json 文件
- [x] 我在插件仓库中写了 README 文件，介绍该插件的使用方法等内容

插件代码仓库地址是：
https://github.com/phantom11235/check_rwx-suid

**Comment by Medicean** [comment]
@phantom11235 

https://github.com/phantom11235/check_rwx-suid/blob/b55f1d5312df47e9d96cf65384945a543c800254/libs/ui.js#L191-L195

将此处的 `clearAll(true)` 改为 `clearAll()` 即可

**Comment by phantom11235** [comment]
> 
> 
> @phantom11235 清空后，再次获取时显示不出来
> 
> https://github.com/phantom11235/check_rwx-suid/blob/b55f1d5312df47e9d96cf65384945a543c800254/libs/ui.js#L191-L195
> 
> 将此处的 `clearAll(true)` 改为 `clearAll()` 即可

抱歉没有测试到这个bug。。谢谢大佬，已修改完成 XD

**Comment by Medicean** [comment]
该已插件上架, 如有更新可在此仓库下重新提 issue

仓库地址： https://github.com/AntSword-Store/check_rwx-suid
版本: 0.1
