### ISSUE TITLE
新增插件 inject_und3ad

### ISSUE THREAD

**Issue by phantom11235** [AntSword-Store/AntSword-Store.github.io#7]
## 新插件上架申请

- [x] 我确定我推出的插件是为了方便网站管理，而不是用于非法用途
- [x] **我保证该插件无后门植入**
- [x] 我确定不存在相同或者相似度很高的插件
- [x] 插件已经在本地测试成功且无较严重Bug
- [x] 我已经按照要求在插件源代码中编写了规范的 package.json 文件
- [x] 我在插件仓库中写了 README 文件，介绍该插件的使用方法等内容

插件代码仓库地址是：
https://github.com/phantom11235/inject_und3ad

**Comment by phantom11235** [comment]
另外想问下大佬， 更新shell信息中的 antSword.ipcRenderer.sendSync('shell-edit', {old: info,new: data })中的info是什么格式，我应该如何构造 XD

**Comment by Medicean** [comment]
https://github.com/AntSwordProject/antSword/blob/master/source/modules/shellmanager/list/contextmenu.js#L328

**Comment by phantom11235** [comment]
> 
> 
> https://github.com/AntSwordProject/antSword/blob/master/source/modules/shellmanager/list/contextmenu.js#L328

啊，其实我找到这里来着 ：），data构造的没错，但是info没构造对。我再自己看下吧哈哈

**Comment by phantom11235** [comment]
已经更新~请大佬审核一下最新的版本~麻烦大佬了

**Comment by phantom11235** [comment]
已经更新，请大佬有空审核下最新版本，麻烦大佬啦

**Comment by phantom11235** [comment]
已经merge，谢谢大佬改正格式及bug XD，技术不好写的仓促，请多见谅

**Comment by Medicean** [comment]
该已插件上架, 如有更新可在此仓库下重新提 issue

仓库地址： https://github.com/AntSword-Store/inject_und3ad
版本: 0.1
